language: cpp
branches: 
 only:
 - guruInterface_v2
sudo: required
virtualenv:
    system_site_packages: true
git:
    submodules: false
    depth: 1
addons:
    homebrew:
        packages:
            - ccache
            - fftw
            - libomp
        update: true
cache: ccache
matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      before_install:
        - git submodule update --init
        - sw_vers
        - python3 -m venv pyenv
        - source pyenv/bin/activate
        - cp make.inc.macosx_clang make.inc
      install:
        - pip install -r python/requirements.txt
      script:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
        - ccache --max-size=5.0G
        - ccache -V && ccache --show-stats && ccache --zero-stats
        - make test
        - make python
    - os: linux
      dist: xenial
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - make docker-wheel
        - ls -lh python/wheelhouse/
        - mkdir -p dist
        - cp python/wheelhouse/finufft*.whl dist/.
