%CNUFFTSPREAD_TYPE1 - 
%
% Syntax:  [Y] = cnufftspread_type1(N, kx, ky, kz, X, eps)
%
% Inputs:
%    N - int
%    eps - double
%    kx - double (M,1)
%    ky - double (M,1)
%    kz - double (M,1)
%    X - complex double (M,1)
%
% Outputs:
%    Y - complex double (N,N,N)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
