FROM quay.io/pypa/manylinux2010_x86_64
LABEL maintainer "Libin Lu"

RUN set -e -x
RUN cd ~; \
curl http://www.fftw.org/fftw-3.3.8.tar.gz --output fftw-3.3.8.tar.gz; \
tar -xvzf fftw-3.3.8.tar.gz; \
cd fftw-3.3.8; \
export CFLAGS=-fPIC; \
./configure --enable-threads --enable-openmp; \
make; \
make install; \
make clean; \
export CFLAGS=-fPIC; \
./configure --enable-threads --enable-openmp --enable-float; \
make; \
make install;

CMD ["/bin/bash"]
