%FINUFFT1D1_MEX - 
%
% Syntax:  [uniform_data] = finufft1d1_mex(N, nonuniform_locations, nonuniform_data, isign, tol, num_threads)
%
% Inputs:
%    N - int
%    isign - int
%    tol - double
%    num_threads - int
%    nonuniform_locations - double (M,1)
%    nonuniform_data - complex double (M,1)
%
% Outputs:
%    uniform_data - complex double (N,1)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
