 #include "finufft_m.h"
/* --------------------------------------------------- */
/* Automatically generated by mwrap                    */
/* --------------------------------------------------- */

/* Code generated by mwrap */
/*
  Copyright statement for mwrap:

  mwrap -- MEX file generation for MATLAB and Octave
  Copyright (c) 2007-2008 David Bindel

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You may distribute a work that contains part or all of the source code
  generated by mwrap under the terms of your choice.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

#include <mex.h>
#include <stdio.h>
#include <string.h>


#ifndef ulong
#  define ulong unsigned long
#endif
#ifndef uint
#  define uint  unsigned int
#endif
#ifndef uchar
#  define uchar unsigned char
#endif


/*
 * Records for call profile.
 */
int* mexprofrecord_= NULL;


/*
 * Support routines for copying data into and out of the MEX stubs
 */

void* mxWrapGetP(const mxArray* a, const char* fmt, const char** e)
{
    void* p = 0;
    mxArray* ap;
    if (mxGetClassID(a) == mxDOUBLE_CLASS && 
        mxGetM(a)*mxGetN(a) == 1 && *mxGetPr(a) == 0)
        return p;
    if (mxIsChar(a)) {
        char pbuf[128];
        mxGetString(a, pbuf, sizeof(pbuf));
        sscanf(pbuf, fmt, &p);
    } 
#ifdef R2008OO
    else if (ap = mxGetProperty(a, 0, "mwptr")) {
        return mxWrapGetP(ap, fmt, e);
    }
#endif
    if (p == 0)
        *e = "Invalid pointer";
    return p;
}

mxArray* mxWrapCreateP(void* p, const char* fmt)
{
    if (p == 0) {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    } else {
        char pbuf[128];
        sprintf(pbuf, fmt, p);
        return mxCreateString(pbuf);
    }
}

mxArray* mxWrapStrncpy(const char* s)
{
    if (s) {
        return mxCreateString(s);
    } else {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    }
}

double mxWrapGetScalar(const mxArray* a, const char** e)
{
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS || mxGetM(a)*mxGetN(a) != 1) {
        *e = "Invalid scalar argument";
        return 0;
    }
    return *mxGetPr(a);
}

char* mxWrapGetString(const mxArray* a, const char** e)
{
    char* s;
    int slen;
    if (!a || (!mxIsChar(a) && mxGetM(a)*mxGetN(a) > 0)) {
        *e = "Invalid string argument";
        return NULL;
    }
    slen = mxGetM(a)*mxGetN(a) + 1;
    s = (char*) mxMalloc(slen);
    if (mxGetM(a)*mxGetN(a) == 0)
        *s = 0;
    else
        mxGetString(a, s, slen);
    return s;
}


#define mxWrapGetArrayDef(func, T) \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    int arraylen; \
    int i; \
    T* p; \
    double* q; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    q = mxGetPr(a); \
    for (i = 0; i < arraylen; ++i) \
        *p++ = (T) (*q++); \
    return array; \
}


#define mxWrapCopyDef(func, T) \
void func(mxArray* a, const T* q, int n) \
{ \
    int i; \
    double* p = mxGetPr(a); \
    for (i = 0; i < n; ++i) \
        *p++ = *q++; \
}


#define mxWrapReturnDef(func, T) \
mxArray* func(const T* q, int m, int n) \
{ \
    int i; \
    double* p; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxREAL); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxREAL); \
        p = mxGetPr(a); \
        for (i = 0; i < m*n; ++i) \
            *p++ = *q++; \
        return a; \
    } \
}


#define mxWrapGetScalarZDef(func, T, ZT, setz) \
void func(T* z, const mxArray* a) \
{ \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    setz(z, (ZT) *pr, (pi ? (ZT) *pi : (ZT) 0)); \
}


#define mxWrapGetArrayZDef(func, T, ZT, setz) \
T* func(const mxArray* a, const char** e) \
{ \
    T* array; \
    int arraylen; \
    int i; \
    T* p; \
    double* qr; \
    double* qi; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    qr = mxGetPr(a); \
    qi = mxGetPi(a); \
    for (i = 0; i < arraylen; ++i) { \
        ZT val_qr = *qr++; \
        ZT val_qi = (qi ? (ZT) *qi++ : (ZT) 0); \
        setz(p, val_qr, val_qi); \
        ++p; \
    } \
    return array; \
}


#define mxWrapCopyZDef(func, T, real, imag) \
void func(mxArray* a, const T* q, int n) \
{ \
    int i; \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    for (i = 0; i < n; ++i) { \
        *pr++ = real(*q); \
        *pi++ = imag(*q); \
        ++q; \
    } \
}


#define mxWrapReturnZDef(func, T, real, imag) \
mxArray* func(const T* q, int m, int n) \
{ \
    int i; \
    double* pr; \
    double* pi; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxCOMPLEX); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxCOMPLEX); \
        pr = mxGetPr(a); \
        pi = mxGetPi(a); \
        for (i = 0; i < m*n; ++i) { \
            *pr++ = real(*q); \
            *pi++ = imag(*q); \
            ++q; \
        } \
        return a; \
    } \
}

#include <complex>

typedef std::complex<double> dcomplex;
#define real_dcomplex(z) std::real(z)
#define imag_dcomplex(z) std::imag(z)
#define setz_dcomplex(z,r,i)  *z = dcomplex(r,i)

typedef std::complex<float> fcomplex;
#define real_fcomplex(z) std::real(z)
#define imag_fcomplex(z) std::imag(z)
#define setz_fcomplex(z,r,i)  *z = fcomplex(r,i)

/* Array copier definitions */
mxWrapGetArrayDef(mxWrapGetArray_bool, bool)
mxWrapCopyDef    (mxWrapCopy_bool,     bool)
mxWrapReturnDef  (mxWrapReturn_bool,   bool)
mxWrapGetArrayDef(mxWrapGetArray_char, char)
mxWrapCopyDef    (mxWrapCopy_char,     char)
mxWrapReturnDef  (mxWrapReturn_char,   char)
mxWrapGetArrayDef(mxWrapGetArray_double, double)
mxWrapCopyDef    (mxWrapCopy_double,     double)
mxWrapReturnDef  (mxWrapReturn_double,   double)
mxWrapGetArrayDef(mxWrapGetArray_float, float)
mxWrapCopyDef    (mxWrapCopy_float,     float)
mxWrapReturnDef  (mxWrapReturn_float,   float)
mxWrapGetArrayDef(mxWrapGetArray_int, int)
mxWrapCopyDef    (mxWrapCopy_int,     int)
mxWrapReturnDef  (mxWrapReturn_int,   int)
mxWrapGetArrayDef(mxWrapGetArray_long, long)
mxWrapCopyDef    (mxWrapCopy_long,     long)
mxWrapReturnDef  (mxWrapReturn_long,   long)
mxWrapGetArrayDef(mxWrapGetArray_size_t, size_t)
mxWrapCopyDef    (mxWrapCopy_size_t,     size_t)
mxWrapReturnDef  (mxWrapReturn_size_t,   size_t)
mxWrapGetArrayDef(mxWrapGetArray_uchar, uchar)
mxWrapCopyDef    (mxWrapCopy_uchar,     uchar)
mxWrapReturnDef  (mxWrapReturn_uchar,   uchar)
mxWrapGetArrayDef(mxWrapGetArray_uint, uint)
mxWrapCopyDef    (mxWrapCopy_uint,     uint)
mxWrapReturnDef  (mxWrapReturn_uint,   uint)
mxWrapGetArrayDef(mxWrapGetArray_ulong, ulong)
mxWrapCopyDef    (mxWrapCopy_ulong,     ulong)
mxWrapReturnDef  (mxWrapReturn_ulong,   ulong)
mxWrapGetScalarZDef(mxWrapGetScalar_fcomplex, fcomplex,
                    float, setz_fcomplex)
mxWrapGetArrayZDef (mxWrapGetArray_fcomplex, fcomplex,
                    float, setz_fcomplex)
mxWrapCopyZDef     (mxWrapCopy_fcomplex, fcomplex,
                    real_fcomplex, imag_fcomplex)
mxWrapReturnZDef   (mxWrapReturn_fcomplex, fcomplex,
                    real_fcomplex, imag_fcomplex)
mxWrapGetScalarZDef(mxWrapGetScalar_dcomplex, dcomplex,
                    double, setz_dcomplex)
mxWrapGetArrayZDef (mxWrapGetArray_dcomplex, dcomplex,
                    double, setz_dcomplex)
mxWrapCopyZDef     (mxWrapCopy_dcomplex, dcomplex,
                    real_dcomplex, imag_dcomplex)
mxWrapReturnZDef   (mxWrapReturn_dcomplex, dcomplex,
                    real_dcomplex, imag_dcomplex)

/* ---- finufft.mw: 57 ----
 * int ier = finufft1d1m(double nj, double[] x, dcomplex[] c, int isign, double eps, double ms, output dcomplex[ms] f, double[] opts);
 */
const char* stubids1_ = "o int = finufft1d1m(i double, i double[], i dcomplex[], i int, i double, i double, o dcomplex[x], i double[])";

void mexStub1(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double      in0_;    /* nj         */
    double*     in1_ =0; /* x          */
    dcomplex*   in2_ =0; /* c          */
    int         in3_;    /* isign      */
    double      in4_;    /* eps        */
    double      in5_;    /* ms         */
    double*     in6_ =0; /* opts       */
    int         out0_;   /* ier        */
    dcomplex*   out1_=0; /* f          */
    int         dim7_;   /* ms         */

    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);

    in0_ = (double) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_dcomplex(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    in3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in4_ = (double) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in5_ = (double) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    out1_ = (dcomplex*) mxMalloc(dim7_*sizeof(dcomplex));
    if (mexprofrecord_)
        mexprofrecord_[1]++;
    out0_ = finufft1d1m(in0_, in1_, in2_, in3_, in4_, in5_, out1_, in6_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim7_, 1, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[1], out1_, dim7_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (out1_) mxFree(out1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- finufft.mw: 97 ----
 * int ier = finufft1d2m(double nj, double[] x, output dcomplex[nj] c, int isign, double eps, double ms, dcomplex[] f, double[] opts);
 */
const char* stubids2_ = "o int = finufft1d2m(i double, i double[], o dcomplex[x], i int, i double, i double, i dcomplex[], i double[])";

void mexStub2(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double      in0_;    /* nj         */
    double*     in1_ =0; /* x          */
    int         in2_;    /* isign      */
    double      in3_;    /* eps        */
    double      in4_;    /* ms         */
    dcomplex*   in5_ =0; /* f          */
    double*     in6_ =0; /* opts       */
    int         out0_;   /* ier        */
    dcomplex*   out1_=0; /* c          */
    int         dim7_;   /* nj         */

    dim7_ = (int) mxWrapGetScalar(prhs[7], &mw_err_txt_);

    in0_ = (double) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    in2_ = (int) mxWrapGetScalar(prhs[2], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in3_ = (double) mxWrapGetScalar(prhs[3], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in4_ = (double) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_dcomplex(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    out1_ = (dcomplex*) mxMalloc(dim7_*sizeof(dcomplex));
    if (mexprofrecord_)
        mexprofrecord_[2]++;
    out0_ = finufft1d2m(in0_, in1_, out1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim7_, 1, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[1], out1_, dim7_);

mw_err_label:
    if (out1_) mxFree(out1_);
    if (in5_)  mxFree(in5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- finufft.mw: 133 ----
 * int ier = finufft1d3m(double nj, double[] x, dcomplex[nj] c, int isign, double eps, double nk, double[] s, output dcomplex[nk] f, double[] opts);
 */
const char* stubids3_ = "o int = finufft1d3m(i double, i double[], i dcomplex[x], i int, i double, i double, i double[], o dcomplex[x], i double[])";

void mexStub3(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double      in0_;    /* nj         */
    double*     in1_ =0; /* x          */
    dcomplex*   in2_ =0; /* c          */
    int         in3_;    /* isign      */
    double      in4_;    /* eps        */
    double      in5_;    /* nk         */
    double*     in6_ =0; /* s          */
    double*     in7_ =0; /* opts       */
    int         out0_;   /* ier        */
    dcomplex*   out1_=0; /* f          */
    int         dim8_;   /* nj         */
    int         dim9_;   /* nk         */

    dim8_ = (int) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: c";        goto mw_err_label;
    }

    in0_ = (double) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_dcomplex(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;
    in3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in4_ = (double) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in5_ = (double) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxGetPr(prhs[6]);
    } else
        in6_ = NULL;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    out1_ = (dcomplex*) mxMalloc(dim9_*sizeof(dcomplex));
    if (mexprofrecord_)
        mexprofrecord_[3]++;
    out0_ = finufft1d3m(in0_, in1_, in2_, in3_, in4_, in5_, in6_, out1_, in7_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim9_, 1, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[1], out1_, dim9_);

mw_err_label:
    if (in2_)  mxFree(in2_);
    if (out1_) mxFree(out1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- finufft.mw: 178 ----
 * int ier = finufft2d1m(double nj, double[] x, double[] y, dcomplex[] c, int isign, double eps, double ms, double mt, output dcomplex[ms, mt] f, double[] opts);
 */
const char* stubids4_ = "o int = finufft2d1m(i double, i double[], i double[], i dcomplex[], i int, i double, i double, i double, o dcomplex[xx], i double[])";

void mexStub4(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double      in0_;    /* nj         */
    double*     in1_ =0; /* x          */
    double*     in2_ =0; /* y          */
    dcomplex*   in3_ =0; /* c          */
    int         in4_;    /* isign      */
    double      in5_;    /* eps        */
    double      in6_;    /* ms         */
    double      in7_;    /* mt         */
    double*     in8_ =0; /* opts       */
    int         out0_;   /* ier        */
    dcomplex*   out1_=0; /* f          */
    int         dim9_;   /* ms         */
    int         dim10_;   /* mt         */

    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);

    in0_ = (double) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_dcomplex(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in5_ = (double) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in6_ = (double) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in7_ = (double) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxGetPr(prhs[8]);
    } else
        in8_ = NULL;
    out1_ = (dcomplex*) mxMalloc(dim9_*dim10_*sizeof(dcomplex));
    if (mexprofrecord_)
        mexprofrecord_[4]++;
    out0_ = finufft2d1m(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, out1_, in8_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim9_, dim10_, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[1], out1_, dim9_*dim10_);

mw_err_label:
    if (in3_)  mxFree(in3_);
    if (out1_) mxFree(out1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- finufft.mw: 229 ----
 * int ier = finufft2d1manym(double ndata, double nj, double[] x, double[] y, dcomplex[] c, int isign, double eps, double ms, double mt, output dcomplex[mtot] f, double[] opts);
 */
const char* stubids5_ = "o int = finufft2d1manym(i double, i double, i double[], i double[], i dcomplex[], i int, i double, i double, i double, o dcomplex[x], i double[])";

void mexStub5(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double      in0_;    /* ndata      */
    double      in1_;    /* nj         */
    double*     in2_ =0; /* x          */
    double*     in3_ =0; /* y          */
    dcomplex*   in4_ =0; /* c          */
    int         in5_;    /* isign      */
    double      in6_;    /* eps        */
    double      in7_;    /* ms         */
    double      in8_;    /* mt         */
    double*     in9_ =0; /* opts       */
    int         out0_;   /* ier        */
    dcomplex*   out1_=0; /* f          */
    int         dim10_;   /* mtot       */

    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);

    in0_ = (double) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (double) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_dcomplex(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    in5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in6_ = (double) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in7_ = (double) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in8_ = (double) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxGetPr(prhs[9]);
    } else
        in9_ = NULL;
    out1_ = (dcomplex*) mxMalloc(dim10_*sizeof(dcomplex));
    if (mexprofrecord_)
        mexprofrecord_[5]++;
    out0_ = finufft2d1manym(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, out1_, in9_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim10_, 1, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[1], out1_, dim10_);

mw_err_label:
    if (in4_)  mxFree(in4_);
    if (out1_) mxFree(out1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- finufft.mw: 272 ----
 * int ier = finufft2d2m(double nj, double[] x, double[] y, output dcomplex[nj] c, int isign, double eps, double ms, double mt, dcomplex[] f, double[] opts);
 */
const char* stubids6_ = "o int = finufft2d2m(i double, i double[], i double[], o dcomplex[x], i int, i double, i double, i double, i dcomplex[], i double[])";

void mexStub6(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double      in0_;    /* nj         */
    double*     in1_ =0; /* x          */
    double*     in2_ =0; /* y          */
    int         in3_;    /* isign      */
    double      in4_;    /* eps        */
    double      in5_;    /* ms         */
    double      in6_;    /* mt         */
    dcomplex*   in7_ =0; /* f          */
    double*     in8_ =0; /* opts       */
    int         out0_;   /* ier        */
    dcomplex*   out1_=0; /* c          */
    int         dim9_;   /* nj         */

    dim9_ = (int) mxWrapGetScalar(prhs[9], &mw_err_txt_);

    in0_ = (double) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    in3_ = (int) mxWrapGetScalar(prhs[3], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in4_ = (double) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in5_ = (double) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in6_ = (double) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxWrapGetArray_dcomplex(prhs[7], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxGetPr(prhs[8]);
    } else
        in8_ = NULL;
    out1_ = (dcomplex*) mxMalloc(dim9_*sizeof(dcomplex));
    if (mexprofrecord_)
        mexprofrecord_[6]++;
    out0_ = finufft2d2m(in0_, in1_, in2_, out1_, in3_, in4_, in5_, in6_, in7_, in8_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim9_, 1, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[1], out1_, dim9_);

mw_err_label:
    if (out1_) mxFree(out1_);
    if (in7_)  mxFree(in7_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- finufft.mw: 317 ----
 * int ier = finufft2d2manym(double ndata, double nj, double[] x, double[] y, output dcomplex[nj, ndata] c, int isign, double eps, double ms, double mt, dcomplex[] f, double[] opts);
 */
const char* stubids7_ = "o int = finufft2d2manym(i double, i double, i double[], i double[], o dcomplex[xx], i int, i double, i double, i double, i dcomplex[], i double[])";

void mexStub7(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double      in0_;    /* ndata      */
    double      in1_;    /* nj         */
    double*     in2_ =0; /* x          */
    double*     in3_ =0; /* y          */
    int         in4_;    /* isign      */
    double      in5_;    /* eps        */
    double      in6_;    /* ms         */
    double      in7_;    /* mt         */
    dcomplex*   in8_ =0; /* f          */
    double*     in9_ =0; /* opts       */
    int         out0_;   /* ier        */
    dcomplex*   out1_=0; /* c          */
    int         dim10_;   /* nj         */
    int         dim11_;   /* ndata      */

    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);

    in0_ = (double) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in1_ = (double) mxWrapGetScalar(prhs[1], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in5_ = (double) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in6_ = (double) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in7_ = (double) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_dcomplex(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;
    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxGetPr(prhs[9]);
    } else
        in9_ = NULL;
    out1_ = (dcomplex*) mxMalloc(dim10_*dim11_*sizeof(dcomplex));
    if (mexprofrecord_)
        mexprofrecord_[7]++;
    out0_ = finufft2d2manym(in0_, in1_, in2_, in3_, out1_, in4_, in5_, in6_, in7_, in8_, in9_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim10_, dim11_, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[1], out1_, dim10_*dim11_);

mw_err_label:
    if (out1_) mxFree(out1_);
    if (in8_)  mxFree(in8_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- finufft.mw: 355 ----
 * int ier = finufft2d3m(double nj, double[] x, double[] y, dcomplex[nj] c, int isign, double eps, double nk, double[] s, double[] t, output dcomplex[nk] f, double[] opts);
 */
const char* stubids8_ = "o int = finufft2d3m(i double, i double[], i double[], i dcomplex[x], i int, i double, i double, i double[], i double[], o dcomplex[x], i double[])";

void mexStub8(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double      in0_;    /* nj         */
    double*     in1_ =0; /* x          */
    double*     in2_ =0; /* y          */
    dcomplex*   in3_ =0; /* c          */
    int         in4_;    /* isign      */
    double      in5_;    /* eps        */
    double      in6_;    /* nk         */
    double*     in7_ =0; /* s          */
    double*     in8_ =0; /* t          */
    double*     in9_ =0; /* opts       */
    int         out0_;   /* ier        */
    dcomplex*   out1_=0; /* f          */
    int         dim10_;   /* nj         */
    int         dim11_;   /* nk         */

    dim10_ = (int) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: c";        goto mw_err_label;
    }

    in0_ = (double) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_dcomplex(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in5_ = (double) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in6_ = (double) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxGetPr(prhs[7]);
    } else
        in7_ = NULL;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxGetPr(prhs[8]);
    } else
        in8_ = NULL;
    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxGetPr(prhs[9]);
    } else
        in9_ = NULL;
    out1_ = (dcomplex*) mxMalloc(dim11_*sizeof(dcomplex));
    if (mexprofrecord_)
        mexprofrecord_[8]++;
    out0_ = finufft2d3m(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, out1_, in9_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim11_, 1, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[1], out1_, dim11_);

mw_err_label:
    if (in3_)  mxFree(in3_);
    if (out1_) mxFree(out1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- finufft.mw: 405 ----
 * int ier = finufft3d1m(double nj, double[] x, double[] y, double[] z, dcomplex[] c, int isign, double eps, double ms, double mt, double mu, output dcomplex[mtot] f, double[] opts);
 */
const char* stubids9_ = "o int = finufft3d1m(i double, i double[], i double[], i double[], i dcomplex[], i int, i double, i double, i double, i double, o dcomplex[x], i double[])";

void mexStub9(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double      in0_;    /* nj         */
    double*     in1_ =0; /* x          */
    double*     in2_ =0; /* y          */
    double*     in3_ =0; /* z          */
    dcomplex*   in4_ =0; /* c          */
    int         in5_;    /* isign      */
    double      in6_;    /* eps        */
    double      in7_;    /* ms         */
    double      in8_;    /* mt         */
    double      in9_;    /* mu         */
    double*     in10_ =0; /* opts       */
    int         out0_;   /* ier        */
    dcomplex*   out1_=0; /* f          */
    int         dim11_;   /* mtot       */

    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);

    in0_ = (double) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_dcomplex(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    in5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in6_ = (double) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in7_ = (double) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in8_ = (double) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in9_ = (double) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[10])*mxGetN(prhs[10]) != 0) {
        in10_ = mxGetPr(prhs[10]);
    } else
        in10_ = NULL;
    out1_ = (dcomplex*) mxMalloc(dim11_*sizeof(dcomplex));
    if (mexprofrecord_)
        mexprofrecord_[9]++;
    out0_ = finufft3d1m(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_, out1_, in10_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim11_, 1, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[1], out1_, dim11_);

mw_err_label:
    if (in4_)  mxFree(in4_);
    if (out1_) mxFree(out1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- finufft.mw: 453 ----
 * int ier = finufft3d2m(double nj, double[] x, double[] y, double[] z, output dcomplex[nj] c, int isign, double eps, double ms, double mt, double mu, dcomplex[] f, double[] opts);
 */
const char* stubids10_ = "o int = finufft3d2m(i double, i double[], i double[], i double[], o dcomplex[x], i int, i double, i double, i double, i double, i dcomplex[], i double[])";

void mexStub10(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double      in0_;    /* nj         */
    double*     in1_ =0; /* x          */
    double*     in2_ =0; /* y          */
    double*     in3_ =0; /* z          */
    int         in4_;    /* isign      */
    double      in5_;    /* eps        */
    double      in6_;    /* ms         */
    double      in7_;    /* mt         */
    double      in8_;    /* mu         */
    dcomplex*   in9_ =0; /* f          */
    double*     in10_ =0; /* opts       */
    int         out0_;   /* ier        */
    dcomplex*   out1_=0; /* c          */
    int         dim11_;   /* nj         */

    dim11_ = (int) mxWrapGetScalar(prhs[11], &mw_err_txt_);

    in0_ = (double) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    in4_ = (int) mxWrapGetScalar(prhs[4], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in5_ = (double) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in6_ = (double) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in7_ = (double) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in8_ = (double) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxWrapGetArray_dcomplex(prhs[9], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in9_ = NULL;
    if (mxGetM(prhs[10])*mxGetN(prhs[10]) != 0) {
        in10_ = mxGetPr(prhs[10]);
    } else
        in10_ = NULL;
    out1_ = (dcomplex*) mxMalloc(dim11_*sizeof(dcomplex));
    if (mexprofrecord_)
        mexprofrecord_[10]++;
    out0_ = finufft3d2m(in0_, in1_, in2_, in3_, out1_, in4_, in5_, in6_, in7_, in8_, in9_, in10_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim11_, 1, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[1], out1_, dim11_);

mw_err_label:
    if (out1_) mxFree(out1_);
    if (in9_)  mxFree(in9_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- finufft.mw: 494 ----
 * int ier = finufft3d3m(double nj, double[] x, double[] y, double[] z, dcomplex[nj] c, int isign, double eps, double nk, double[] s, double[] t, double[] u, output dcomplex[nk] f, double[] opts);
 */
const char* stubids11_ = "o int = finufft3d3m(i double, i double[], i double[], i double[], i dcomplex[x], i int, i double, i double, i double[], i double[], i double[], o dcomplex[x], i double[])";

void mexStub11(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    double      in0_;    /* nj         */
    double*     in1_ =0; /* x          */
    double*     in2_ =0; /* y          */
    double*     in3_ =0; /* z          */
    dcomplex*   in4_ =0; /* c          */
    int         in5_;    /* isign      */
    double      in6_;    /* eps        */
    double      in7_;    /* nk         */
    double*     in8_ =0; /* s          */
    double*     in9_ =0; /* t          */
    double*     in10_ =0; /* u          */
    double*     in11_ =0; /* opts       */
    int         out0_;   /* ier        */
    dcomplex*   out1_=0; /* f          */
    int         dim12_;   /* nj         */
    int         dim13_;   /* nk         */

    dim12_ = (int) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (int) mxWrapGetScalar(prhs[13], &mw_err_txt_);

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim12_) {
        mw_err_txt_ = "Bad argument size: c";        goto mw_err_label;
    }

    in0_ = (double) mxWrapGetScalar(prhs[0], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxGetPr(prhs[1]);
    } else
        in1_ = NULL;
    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxGetPr(prhs[2]);
    } else
        in2_ = NULL;
    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxGetPr(prhs[3]);
    } else
        in3_ = NULL;
    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_dcomplex(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;
    in5_ = (int) mxWrapGetScalar(prhs[5], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in6_ = (double) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    in7_ = (double) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    if (mw_err_txt_)
        goto mw_err_label;
    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxGetPr(prhs[8]);
    } else
        in8_ = NULL;
    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxGetPr(prhs[9]);
    } else
        in9_ = NULL;
    if (mxGetM(prhs[10])*mxGetN(prhs[10]) != 0) {
        in10_ = mxGetPr(prhs[10]);
    } else
        in10_ = NULL;
    if (mxGetM(prhs[11])*mxGetN(prhs[11]) != 0) {
        in11_ = mxGetPr(prhs[11]);
    } else
        in11_ = NULL;
    out1_ = (dcomplex*) mxMalloc(dim13_*sizeof(dcomplex));
    if (mexprofrecord_)
        mexprofrecord_[11]++;
    out0_ = finufft3d3m(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_, in10_, out1_, in11_);
    plhs[0] = mxCreateDoubleMatrix(1, 1, mxREAL);
    *mxGetPr(plhs[0]) = out0_;
    plhs[1] = mxCreateDoubleMatrix(dim13_, 1, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[1], out1_, dim13_);

mw_err_label:
    if (in4_)  mxFree(in4_);
    if (out1_) mxFree(out1_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ----
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[])
{
    char id[512];
    if (nrhs == 0) {
        mexPrintf("Mex function installed\n");
        return;
    }

    if (mxGetString(prhs[0], id, sizeof(id)) != 0)
        mexErrMsgTxt("Identifier should be a string");
    else if (strcmp(id, stubids1_) == 0)
        mexStub1(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids2_) == 0)
        mexStub2(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids3_) == 0)
        mexStub3(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids4_) == 0)
        mexStub4(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids5_) == 0)
        mexStub5(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids6_) == 0)
        mexStub6(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids7_) == 0)
        mexStub7(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids8_) == 0)
        mexStub8(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids9_) == 0)
        mexStub9(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids10_) == 0)
        mexStub10(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids11_) == 0)
        mexStub11(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, "*profile on*") == 0) {
        if (!mexprofrecord_) {
            mexprofrecord_ = (int*) malloc(12 * sizeof(int));
            mexLock();
        }
        memset(mexprofrecord_, 0, 12 * sizeof(int));
    } else if (strcmp(id, "*profile off*") == 0) {
        if (mexprofrecord_) {
            free(mexprofrecord_);
            mexUnlock();
        }
        mexprofrecord_ = NULL;
    } else if (strcmp(id, "*profile report*") == 0) {
        if (!mexprofrecord_)
            mexPrintf("Profiler inactive\n");
        mexPrintf("%d calls to finufft.mw:57\n", mexprofrecord_[1]);
        mexPrintf("%d calls to finufft.mw:97\n", mexprofrecord_[2]);
        mexPrintf("%d calls to finufft.mw:133\n", mexprofrecord_[3]);
        mexPrintf("%d calls to finufft.mw:178\n", mexprofrecord_[4]);
        mexPrintf("%d calls to finufft.mw:229\n", mexprofrecord_[5]);
        mexPrintf("%d calls to finufft.mw:272\n", mexprofrecord_[6]);
        mexPrintf("%d calls to finufft.mw:317\n", mexprofrecord_[7]);
        mexPrintf("%d calls to finufft.mw:355\n", mexprofrecord_[8]);
        mexPrintf("%d calls to finufft.mw:405\n", mexprofrecord_[9]);
        mexPrintf("%d calls to finufft.mw:453\n", mexprofrecord_[10]);
        mexPrintf("%d calls to finufft.mw:494\n", mexprofrecord_[11]);
    } else if (strcmp(id, "*profile log*") == 0) {
        FILE* logfp;
        if (nrhs != 2 || mxGetString(prhs[1], id, sizeof(id)) != 0)
            mexErrMsgTxt("Must have two string arguments");
        logfp = fopen(id, "w+");
        if (!logfp)
            mexErrMsgTxt("Cannot open log for output");
        if (!mexprofrecord_)
            fprintf(logfp, "Profiler inactive\n");
        fprintf(logfp, "%d calls to finufft.mw:57\n", mexprofrecord_[1]);
        fprintf(logfp, "%d calls to finufft.mw:97\n", mexprofrecord_[2]);
        fprintf(logfp, "%d calls to finufft.mw:133\n", mexprofrecord_[3]);
        fprintf(logfp, "%d calls to finufft.mw:178\n", mexprofrecord_[4]);
        fprintf(logfp, "%d calls to finufft.mw:229\n", mexprofrecord_[5]);
        fprintf(logfp, "%d calls to finufft.mw:272\n", mexprofrecord_[6]);
        fprintf(logfp, "%d calls to finufft.mw:317\n", mexprofrecord_[7]);
        fprintf(logfp, "%d calls to finufft.mw:355\n", mexprofrecord_[8]);
        fprintf(logfp, "%d calls to finufft.mw:405\n", mexprofrecord_[9]);
        fprintf(logfp, "%d calls to finufft.mw:453\n", mexprofrecord_[10]);
        fprintf(logfp, "%d calls to finufft.mw:494\n", mexprofrecord_[11]);
        fclose(logfp);
    } else
        mexErrMsgTxt("Unknown identifier");
}

