%FINUFFT3D1_MEX - 
%
% Syntax:  [uniform_data] = finufft3d1_mex(N1, N2, N3, nonuniform_locations, nonuniform_data, isign, tol, num_threads)
%
% Inputs:
%    N1 - int
%    N2 - int
%    N3 - int
%    isign - int
%    tol - double
%    num_threads - int
%    nonuniform_locations - double (M,3)
%    nonuniform_data - complex double (M,1)
%
% Outputs:
%    uniform_data - complex double (N1,N2,N3)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
