#ifndef DIRFT_H
#define DIRFT_H

#include "utils.h"
#include "utils_fp.h"

void dirft1d1(CUFINUFFT_BIGINT nj,CUFINUFFT_FLT* x,CUFINUFFT_CPX* c,int isign,CUFINUFFT_BIGINT ms, CUFINUFFT_CPX* f);
void dirft1d2(CUFINUFFT_BIGINT nj,CUFINUFFT_FLT* x,CUFINUFFT_CPX* c,int iflag,CUFINUFFT_BIGINT ms, CUFINUFFT_CPX* f);
void dirft1d3(CUFINUFFT_BIGINT nj,CUFINUFFT_FLT* x,CUFINUFFT_CPX* c,int iflag,CUFINUFFT_BIGINT nk, CUFINUFFT_FLT* s, CUFINUFFT_CPX* f);

void dirft2d1(CUFINUFFT_BIGINT nj,CUFINUFFT_FLT* x,CUFINUFFT_FLT *y,CUFINUFFT_CPX* c,int iflag,CUFINUFFT_BIGINT ms, CUFINUFFT_BIGINT mt, CUFINUFFT_CPX* f);
void dirft2d2(CUFINUFFT_BIGINT nj,CUFINUFFT_FLT* x,CUFINUFFT_FLT *y,CUFINUFFT_CPX* c,int iflag,CUFINUFFT_BIGINT ms, CUFINUFFT_BIGINT mt, CUFINUFFT_CPX* f);
void dirft2d3(CUFINUFFT_BIGINT nj,CUFINUFFT_FLT* x,CUFINUFFT_FLT *y,CUFINUFFT_CPX* c,int iflag,CUFINUFFT_BIGINT nk, CUFINUFFT_FLT* s, CUFINUFFT_FLT* t, CUFINUFFT_CPX* f);

void dirft3d1(CUFINUFFT_BIGINT nj,CUFINUFFT_FLT* x,CUFINUFFT_FLT *y,CUFINUFFT_FLT *z,CUFINUFFT_CPX* c,int iflag,CUFINUFFT_BIGINT ms, CUFINUFFT_BIGINT mt, CUFINUFFT_BIGINT mu, CUFINUFFT_CPX* f);
void dirft3d2(CUFINUFFT_BIGINT nj,CUFINUFFT_FLT* x,CUFINUFFT_FLT *y,CUFINUFFT_FLT *z,CUFINUFFT_CPX* c,int iflag,CUFINUFFT_BIGINT ms, CUFINUFFT_BIGINT mt, CUFINUFFT_BIGINT mu, CUFINUFFT_CPX* f);
void dirft3d3(CUFINUFFT_BIGINT nj,CUFINUFFT_FLT* x,CUFINUFFT_FLT *y,CUFINUFFT_FLT *z,CUFINUFFT_CPX* c,int iflag,CUFINUFFT_BIGINT nk, CUFINUFFT_FLT* s, CUFINUFFT_FLT* t, CUFINUFFT_FLT *u, CUFINUFFT_CPX* f);

#endif
