Makefile for FINUFFT. Please specify your task:
 make lib - build the main CPU library (in lib/ and lib-static/)
 make install PREFIX=<dir> - install the CPU library and its headers
 make cufinufft - build the GPU library (needs the CUDA toolkit)
 make checkgpu - compile and run quick GPU math validation tests
 make examples - compile and run all codes in examples/
 make test - compile and run quick math validation tests
 make fortran - compile and run Fortran tests and examples
 make matlab - compile MATLAB interfaces (no test)
 make octave - compile then test octave interfaces
 make python - compile then test python interfaces
 make spreadtest - compile & run spreader-only perf tests
 make spreadtestsweep - spreader-only perf tests, sweep all tols
 make perftest - compile and run some performance tests (~1 min)
 make all - do all the above (~3 min; assumes have MEX, etc)
 make objclean - remove all object files, preserving libs & MEX
 make clean - also remove all lib, MEX, py, and demo executables
 make setup - check (and possibly download) dependencies
 make setupclean - delete downloaded dependencies (try if errors)
 make web - build HTML docs and serve at http://localhost:8042
For faster (multicore) compilation, append, for example, -j8

Make options:
 'make [task] OMP=OFF' for single-threaded (no refs to OpenMP)
 'make [task] FFT=DUCC' for DUCC0 FFT (otherwise uses FFTW3)
 'make [task] LTO=OFF' disable link time optimization
 You must at least 'make objclean' before changing such options!

Also see docs/install.rst and docs/README
