name: Run perftests

on:
  push:
    branches:
      - master

jobs:
  perftest:
    strategy:
      matrix:
        target:
          - name: "fftw"
            ducc_enabled: "OFF"
          - name: "ducc"
            ducc_enabled: "ON"
    env:
      VERSIONS_INPUT: v2.2.0 v2.3.1 v2.4.1 v2.5.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest perftest
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          cmake: true
          ninja: true

      - name: Checkout tagged versions
        run: |
          mkdir -p ../builds
          rm -fr ../builds/*
          tags="$VERSIONS_INPUT master"
          for tag in $tags; do
            if [ "$tag" = "master" ]; then
              src_path="."
            else
              rm -fr ../$tag
              git worktree add -f -d ../$tag tags/$tag
              rm -fr ../$tag/perftest
              cp -r perftest ../$tag/perftest
              src_path="../$tag"
            fi
            cmake -B ../builds/$tag -S $src_path -DFINUFFT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DFINUFFT_USE_DUCC0=${{ matrix.target.ducc_enabled }} &&
            cmake --build ../builds/$tag --target perftest -j
          done

      - name: Install plotting dependency
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - run: python3 -m pip install --quiet matplotlib pandas Jinja2 py-cpuinfo

      - name: Generate docs page
        run: |
          rm -f outputs
          mkdir -p outputs
          python3 perftest/run_perftest_ci.py \
            --backend "${{ matrix.target.name }}" \
            --builds-root ../builds \
            --tag-list "$VERSIONS_INPUT master" \
            --page-template docs/performance_backend.rst.j2 \
            --output outputs

      - uses: actions/upload-artifact@v4
        with:
          name: perftest-result-${{ matrix.target.name }}
          path: ./outputs/

  gather-matrix-results:
    needs: perftest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: perftest-result-*
          path: ./outputs/
          merge-multiple: true

      - name: Move results
        run: |
          rm -fr docs/pics/perftestci_*
          mv outputs/*.rst docs/
          mv outputs/*.png docs/pics/

      - name: Commit generated perftest docs
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@github.com"
          git checkout -B perftest-results
          git add docs/pics/perftestci_* docs/*.rst
          git diff --staged --quiet || git commit -m "Generated new perftest report page. [no ci]" && git push -f --set-upstream origin perftest-results
